apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 31321
    hostPort: 31321
  - containerPort: 31300
    hostPort: 31300
  - containerPort: 80   # For LoadBalancer services
    hostPort: 9090      # 8080 is used by ArgoCD
  - containerPort: 443  # For HTTPS LoadBalancer services
    hostPort: 9043      # 8443 is used by ArgoCD
- role: worker
- role: worker
